name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  common:
    path: ../common
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.3
  lints: ^2.0.0
  test: ^1.21.0